# Generated by Django 3.1.4 on 2021-08-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210803_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
